### ISSUE TITLE
TODOs and its spec(~8/15)

### ISSUE THREAD

**Issue by MKRoughDiamond** [MKRoughDiamond/papillon#1]
### TODOs

* Implement Databases(Item, Research, Craft)
* Implement Map movement(Including UI)
* Implement Crafting mechanism
* Make some examples to test its functions
* (if you can,) Implement Interfaces for technology, and crafting

### Spec

1. Database
- Initialize : You `must` get data from files. it should be better using similar form to ItemData.
- Search : Of course, we will make small items, so you may not optimize it.

2. Map movement
- Map generating is ALMOST completed. (Use Ramdom.Range for random generate)
- GameManager(or BoardManager) will hold `Map`, and display it into `canvas/map`
- If you want, merge `prefab` to `Development` first.(and should)

3. Crafting mechanism
- Maybe you have enough classes to implement these functions. (do not make TOO MUCH classes)
- Makes some items, and crafting recipes first(dummy data, not include icons)
- Use `Debug.Log` for the tests.(like CUI game)

4. Interfaces for technology, and Crafting
- it means make some list(table?)s that can be scrolled.
- it will be hard work, but good luck :D

### NOTICE
- Good comments makes good program : I cannot understand what you make without comments. I know It is very bothering and boring work, but it is needed.
- I have some schedules to 8/15, so we'd better to meet 8/16. We will check its progress and do other TODOs.
- I hope we get good BYEONG TEUK companies.

If you want more specific spec, leave some replies and talk to me.(with kakaotalk)

**Comment by ryanking13** [comment]
looks like "do everything" lol
