### ISSUE TITLE
spec of field for item farming and TODOs

### ISSUE THREAD

**Issue by MKRoughDiamond** [MKRoughDiamond/papillon#2]
## field spec
* add list of `itemholder` variable in field class(maybe it will need it.)
* `itemholder`
  - this class should be modified
  - add position(x, y) and size(x, y)
  - it holds sprite for displaying dropped items.
* interaction
  - when click itemholder, we can get 1 drop item
  - if we have pickaxe or other tools, we can get more items
  - do not explain what will be dropped and other effects during harvesting. : reduce our plan
  - when some effect occurs(cannot mine or get hurt), show these effect

## satiety
* each interation (use items, mine, etc.) will reduce satiety.
* if satiety < 0, game over.

## factory, research, farm
* i think we should reduce our plan
  - just upgrade our facilities.(do not place blocks etc.)
  - maybe we will use just panels.

## TODOs
* item generation
* remove other scenes.(just leave panels)
* add satiety and easy effects(get hurts, etc.)

**Comment by ryanking13** [comment]
please tell me field size (X*Y) and each tile/block size for testing
